

# Instance Id
spring:
  application:
    instance_id: dockercli


  # Logging
  zipkin:
    enabled: true
    base-url: http://ZipkinServer:9411/
  logging:
    logstash:
      url: logstashserver
      tcp-port: 5000
      tcp-input: ${logging.logstash.url}:${logging.logstash.tcp-port}


  # RabbitMQ
  rabbitmq:
    host: RabbitMQ-Server
    port: 5672
    username: guest
    password: guest


  # Web-Utils Configuration
  web-utils:
    data:
      # Postgres DataSource
      datasource:
        # Connection Properties
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://PostgresDatabase:5432/cloud_db?currentSchema=accounts
        username: dbo_admin
        password: rootroot
    security:
      oauth2-resource:
        remote-token-services:
          client-id: default_oauth2_client_id
          client-secret: QWERTY74gray75raccoon634
          check-token-url: http://ZuulApiProxy:8081/auth-ms/oauth/check_token


# Server Properties
server:
  port: 9871
  servlet:
    context-path: /accounts-ms


# Eureka client properties
eureka:
  client:
    serviceUrl:
      defaultZone: http://EurekaServer:8761/eureka
