
info:
  component: Accounts Ms


spring:
  application:
    name: accounts-ms
    instance_id: dev


  # Logging    
  sleuth:
    sampler:
      probability: 0.2  # 20.0% Sampling
  zipkin:
    enabled: ${ZIPKIN_ENABLED:true}
    base-url: ${ZIPKIN_SERVER:http://localhost:9411/}

  logging:
    logstash:
      url: ${LOGSTASH_URL:localhost}
      tcp-port: ${LOGSTASH_TCP_PORT:5000}
      tcp-input: ${logging.logstash.url}:${logging.logstash.tcp-port}


  rabbitmq:
    host: ${RABBIT_MQ_URL:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}


  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false



server:
  port: ${SERVER_PORT:9871}
  servlet:
    context-path: /accounts-ms

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  endpoint:
    health:
      show-details: always


security:
  signing-key: xja6jeEyKKX5HpJ #https://www.random.org/strings/
  security-realm: Spring Cloud Sample Stack
  jwt:
    local-resource-id: accounts-ms-resource-id



## Eureka client properties ##
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.int}}
      management:
        context-path: ${server.servlet.context-path}/actuator
        port: ${server.port}
    #nonSecurePort: 8088
    statusPageUrlPath: ${server.servlet.context-path}/actuator/info
    healthCheckUrlPath: ${server.servlet.context-path}/actuator/health
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    registerWithEureka: true
    healthcheck:
      enabled: true
    fetchRegistry: false


##Hystrix##
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
