
spring:
  application:
    name: accounts-ms
    instance_id: dev
  
  # Logging    
  sleuth:
    sampler:
      probability: 0.2  # 20.0% Sampling
  zipkin:
    enabled: ${ZIPKIN_ENABLED:true}
    base-url: ${ZIPKIN_SERVER:http://localhost:9411/}

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false



server:
  port: ${SERVER_PORT:9871}
  servlet:
    context-path: /accounts-ms

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  endpoint:
    health:
      show-details: always
 

## Eureka client properties ##
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.int}}
      management:
        context-path: ${server.servlet.context-path}/actuator
        port: ${server.port}
    #nonSecurePort: 8088
    statusPageUrlPath: ${server.servlet.context-path}/actuator/info
    healthCheckUrlPath: ${server.servlet.context-path}/actuator/health
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    registerWithEureka: true
    healthcheck:
      enabled: true
    fetchRegistry: false


##Hystrix##
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
