

# Instance Id
spring:
  application:
    instance_id: swarm


  # Logging
  zipkin:
    enabled: true
    base-url: http://tasks.ZipkinServer:9411/
  logging:
    logstash:
      url: tasks.logstashserver
      tcp-port: 5000
      tcp-input: ${logging.logstash.url}:${logging.logstash.tcp-port}


  # RabbitMQ
  rabbitmq:
    host: tasks.RabbitMQ-Server
    port: 5672
    username: guest
    password: guest


  # Web-Utils Configuration
  web-utils:
    data:
      # Postgres DataSource
      datasource:
        # Connection Properties
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://tasks.PostgresDatabase:5432/cloud_db?currentSchema=auth
        username: dbo_admin
        password: rootroot


# Server Properties
server:
  port: 9869
  servlet:
    context-path: /auth-ms


# Eureka client properties
eureka:
  client:
    serviceUrl:
      defaultZone: http://tasks.EurekaServer:8761/eureka
