

# Info
info:
  component: Auth Ms


# App name
spring:
  application:
    name: auth-ms


  # Logging
  sleuth:
    sampler:
      probability: 0.2  # 20.0% Sampling
  zipkin:
    sender:
      type: web
    enabled: ${ZIPKIN_ENABLED:true}
    base-url: ${ZIPKIN_SERVER:http://localhost:9411/}
  logging:
    logstash:
      url: ${LOGSTASH_URL:localhost}
      tcp-port: ${LOGSTASH_TCP_PORT:5000}
      tcp-input: ${logging.logstash.url}:${logging.logstash.tcp-port}


  # RabbitMQ
  rabbitmq:
    host: ${RABBIT_MQ_URL:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}


  # Spring cloud stream channels
  cloud.stream.bindings:
    consumerUserCreatedMessageChannel:
      destination: users.events.created
    consumerUserUpdatedMessageChannel:
      destination: users.events.updated
    consumerUserDeletedMessageChannel:
      destination: users.events.deleted


  # Network preferences
  cloud.inetutils:
    ignored-interfaces:
      - docker0
      - veth.*
    preferred-networks:
      - 192.168
      - 10.0


  # Jackson configuration
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false


  # Database global config
  jpa:
    database: default
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true


  # Configure flyway schemas for auth-ms
  flyway:
    schemas: ${POSTGRES_DATABASE_SCHEMA:auth}
    locations: classpath:db/migration,classpath:db/data


  # Web-Utils Configuration
  web-utils:
    tasks:
      maxPoolSize: 100
      corePoolSize: 30
      queueCapacity: 200
    data:
      enabled: true
      # Jpa Entities Package
      entities-package: com.grayraccoon.sample.authms.data.postgres.domain
      persistence-unit: authMs

      heroku:
        url-env-name: HEROKU_THE_DB_URL
        db-schema: ${POSTGRES_DATABASE_SCHEMA:auth}
        db-type: postgresql

      # Postgres DataSource
      datasource:
        # Connection Properties
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://${POSTGRES_DATABASE_HOST:localhost}:${POSTGRES_DATABASE_PORT:5432}/${POSTGRES_DATABASE_DBNAME:cloud_db}?currentSchema=${POSTGRES_DATABASE_SCHEMA:auth}
        username: ${POSTGRES_DATABASE_USER:dbo_admin}
        password: ${POSTGRES_DATABASE_PASS:root}

        # Pool Properties
        maximumPoolSize: 3
        minimumIdle: 1

        #Connection test timing and intervals properties
        connectionTimeout: 30000
        idleTimeout: 600000
        maxLifetime: 1200000

    #Cors Config
    web:
      allow-all-cors: false

    # Security Config
    security:
      oauth2-server:
        enabled: true
        signing-key: xja6jeEyKKX5HpJ #https://www.random.org/strings/ 15 length
        security-realm: Spring Cloud Sample Stack
      oauth2-resource:
        enabled: true
        local-resource-id: auth-ms-resource-id
        secured-matchers: >
          /**/authenticated/**,
          /**/secured/**


# Server Properties
server:
  port: ${SERVER_PORT:9869}
  servlet:
    context-path: /auth-ms


# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  endpoint:
    health:
      show-details: always



# Eureka client properties
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.int}}
      management:
        context-path: ${server.servlet.context-path}/actuator
        port: ${server.port}
    #nonSecurePort: 8088
    statusPageUrlPath: ${server.servlet.context-path}/actuator/info
    healthCheckUrlPath: ${server.servlet.context-path}/actuator/health
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    registerWithEureka: true
    healthcheck:
      enabled: true
    fetchRegistry: false
    registryFetchIntervalSeconds: 5


# Hystrix Configuration
hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
