

# Info
info:
  component: Eureka Server


# Server Properties
server:
  port:
    port: ${SERVER_PORT:8761}


# App name
spring:
  application:
    name: eureka-server


# Eureka server properties
eureka:
  server:
    eviction-interval-timer-in-ms: 5000
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
