

spring:
  application:
    name: oauth2-ms-sample
    instance_id: dev
  
  # Logging    
  sleuth:
    sampler:
      probability: 0.6  # 60.0% Sampling
  zipkin:
    enabled: ${ZIPKIN_ENABLED:true}
    base-url: ${ZIPKIN_SERVER:http://localhost:9411/}
  
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  
  jpa:
    database: default
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  
  
  datasource:
    postgres:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: rootroot

      initial-size: 1
      max-active: 10
      max-idle: 10
      test-on-borrow: true
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 30000
      max-wait: 10000
      min-evictable-idle-time-millis: 30000
      log-abandoned: true
      test-while-idle: true
      validation-interval: 300000
      jdbc-interceptors: org.apache.tomcat.jdbc.pool.interceptor.SlowQueryReport(threshold=10000)


server:
  port: ${SERVER_PORT:9869}
  servlet:
    context-path: /oauth2-ms-sample

management:
  endpoints:
    web:
      exposure:
        include: heapdump,liquibase,loggers,prometheus,threaddump,info,metrics,health,hystrix.stream

security:
  signing-key: xja6jeEyKKX5HpJ #https://www.random.org/strings/
  security-realm: Sample Default Realm
  jwt:
    users-resource-id: usersjwtresourceid



## Eureka client properties ##
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.int}}
      management:
        context-path: ${server.servlet.context-path}
        port: ${server.port}
    #nonSecurePort: 8088
    statusPageUrlPath: ${server.servlet.context-path}/actuator/info
    healthCheckUrlPath: ${server.servlet.context-path}/actuator/health
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    registerWithEureka: true
    healthcheck:
      enabled: true
    fetchRegistry: false


##Hystrix##
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
