
server:
  port: ${SERVER_PORT:8760}

spring:
  application:
    name: SpringAdminServer
  config:
    name: SpringAdminServer

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    instance:
      metadataMap:
        instanceId: ${spring.application.name}:${server.port}
    registerWithEureka: true
    healthcheck:
      enabled: true
    fetchRegistry: true
