
info:
  component: Spring Admin Server

server:
  port: ${SERVER_PORT:8760}

spring:
  application:
    name: Spring-Admin-Server
  config:
    name: SpringAdminServer

  security:
    oauth2:
      client:
        registration:
          custom-client:
            provider: custom-provider
            client-id: default_oauth2_client_id
            client-secret: QWERTY74gray75raccoon634
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            scope: read
            #redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Login Client
        provider:
          custom-provider:
            authorization-uri: http://localhost:8080/auth-ms/oauth/authorize
            token-uri: http://localhost:8080/auth-ms/oauth/token
            user-info-uri: http://localhost:8080/auth-ms/ws/authenticated/user
            user-name-attribute: username


management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    instance:
      metadataMap:
        instanceId: ${spring.application.name}:${server.port}
    registerWithEureka: true
    healthcheck:
      enabled: true
    fetchRegistry: true
