
info:
  component: Spring Admin Server

server:
  port: ${SERVER_PORT:8760}

spring:
  application:
    name: spring-admin-server
  config:
    name: SpringAdminServer


  #Don't ignore headers, oauth2 secured endpoints require Authorization and Cookies to work
  boot:
    admin:
      ui:
        public-url: http://localhost:8082/admin/
      instance-proxy:
        ignored-headers:


security:
  oauth2:
    client:
      grant-type: authorization_code
      accessTokenUri: http://localhost:8081/auth-ms/oauth/token
      userAuthorizationUri: http://localhost:8081/auth-ms/oauth/authorize
      clientId: default_oauth2_client_id
      clientSecret: QWERTY74gray75raccoon634

      use-current-uri: false
      registered-redirect-uri: http://localhost:8760/login
      pre-established-redirect-uri: http://localhost:8760/login
    resource:
      userInfoUri: http://localhost:8081/auth-ms/ws/authenticated/user




management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    instance:
      metadataMap:
        instanceId: ${spring.application.name}:${server.port}
    registerWithEureka: true
    healthcheck:
      enabled: true
    fetchRegistry: true
