

# Info
info:
  component: Turbine Server


# Server Properties
server:
  port: ${SERVER_PORT:9003}
  servlet:
    context-path: /


# App name
spring:
  application:
    name: turbine-server
  config:
    name: turbine-server


  # Network preferences
  cloud.inetutils:
    ignored-interfaces:
      - docker0
      - veth.*
    preferred-networks:
      - 192.168
      - 10.0


# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: info,health
      base-path: /actuator
  endpoint:
    health:
      show-details: always


# Turbine Clusters
turbine:
  aggregator:
    clusterConfig: ACCOUNTS-MS,AUTH-MS
  app-config: accounts-ms,auth-ms
  instanceUrlSuffix:
    ACCOUNTS-MS: /accounts-ms/actuator/hystrix.stream
    AUTH-MS: /auth-ms/actuator/hystrix.stream
  combine-host-port: true


# Eureka client properties
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.int}}
      management:
        context-path: ${server.servlet.context-path}/actuator
        port: ${server.port}
    #nonSecurePort: 8088
    statusPageUrlPath: ${server.servlet.context-path}/actuator/info
    healthCheckUrlPath: ${server.servlet.context-path}/actuator/health
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    instance:
      metadataMap:
        instanceId: ${spring.application.name}:${server.port}
    registerWithEureka: true
    healthcheck:
      enabled: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
