
info:
  component: UI Gateway

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /

spring:
  application:
    name: ui-gateway
  config:
    name: UiGateway

  # Logging
  sleuth:
    sampler:
      probability: 0.2  # 20.0% Sampling
  zipkin:
    enabled: ${ZIPKIN_ENABLED:true}
    base-url: ${ZIPKIN_SERVER:http://localhost:9411/}

  logging:
    logstash:
      url: ${LOGSTASH_URL:localhost}
      tcp-port: ${LOGSTASH_TCP_PORT:5000}
      tcp-input: ${logging.logstash.url}:${logging.logstash.tcp-port}


  rabbitmq:
    host: ${RABBIT_MQ_URL:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}


spring.security.oauth2.client:
  registration:
    custom-client:
      provider: custom-provider
      client-id: default_oauth2_client_id
      client-secret: QWERTY74gray75raccoon634
      client-authentication-method: basic
      authorization-grant-type: authorization_code
      scope: read
      redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
      client-name: Login Client
  provider:
    custom-provider:
      authorization-uri: http://localhost:8081/auth-ms/oauth/authorize
      token-uri: http://localhost:8081/auth-ms/oauth/token
      user-info-uri: http://localhost:8081/auth-ms/ws/authenticated/user
      user-name-attribute: username


# https://aboullaite.me/spring-cloud-gateway/
spring.cloud.gateway:
  enabled: true
  routes:
    - predicates:
        - Path=/eureka
      filters:
        - StripPrefix=1
      uri: http://localhost:8761/
    - predicates:
        - Path=/eureka/**
      filters:
        - StripPrefix=0
        #- RewritePath=/eureka/(?<segment>.*), /bar/$\{segment}
      uri: http://localhost:8761/


    - predicates:
        - Path=/admin/**
      filters:
        - StripPrefix=1
        - TokenRelay=
      uri: lb://Spring-Admin-Server/

    - predicates:
        - Path=/hy/**
      filters:
        - StripPrefix=0
        - TokenRelay=
      uri: lb://Hystrix-Dashboard/

    - predicates:
        - Path=/tb/**
      filters:
        - StripPrefix=1
        - TokenRelay=
      uri: lb://turbine-server/

    - predicates:
        - Path=/turbine.stream**
        - RemoteAddr=192.168.0.0/24
      filters:
        - StripPrefix=0
        - TokenRelay=
        #- RewritePath=/(?<turbine>.*), /tb/$\{turbine}
      uri: lb://turbine-server/



management:
  endpoints:
    web:
      exposure:
        include: info,health
      base-path: /actuator
  endpoint:
    health:
      show-details: always



eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.int}}
      management:
        context-path: ${server.servlet.context-path}/actuator
        port: ${server.port}
    #nonSecurePort: 8088
    statusPageUrlPath: ${server.servlet.context-path}/actuator/info
    healthCheckUrlPath: ${server.servlet.context-path}/actuator/health
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    instance:
      metadataMap:
        instanceId: ${spring.application.name}:${server.port}
    registerWithEureka: true
    healthcheck:
      enabled: true
    fetchRegistry: true


error:
  whitelabel:
    enabled: false

