
spring:
  application:
    name: users-ms-sample
    instance_id: dev

server:
  port: ${SERVER_PORT:9871}
  servlet:
    context-path: /users-ms-sample

management:
  endpoints:
    web:
      exposure:
        include: heapdump,liquibase,loggers,prometheus,threaddump,info,metrics,health,hystrix.stream
 

## Eureka client properties ##
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.int}}
      management:
        context-path: ${server.servlet.context-path}
        port: ${server.port}
    #nonSecurePort: 8088
    statusPageUrlPath: ${server.servlet.context-path}/actuator/info
    healthCheckUrlPath: ${server.servlet.context-path}/actuator/health
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    healthcheck:
      enabled: true
    fetchRegistry: false

##Hystrix##
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
