

# Server Properties
server:
  port: 8081


spring:
  # Logging
  zipkin:
    enabled: true
    base-url: http://ZipkinServer:9411/
  logging:
    logstash:
      url: logstashserver
      tcp-port: 5000
      tcp-input: ${logging.logstash.url}:${logging.logstash.tcp-port}


  # RabbitMQ
  rabbitmq:
    host: RabbitMQ-Server
    port: 5672
    username: guest
    password: guest


# Eureka client properties
eureka:
  client:
    serviceUrl:
      defaultZone: http://EurekaServer:8761/eureka
