
info:
  component: Zuul Proxy App

server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ZuulProxy
  config:
    name: ZuulProxy

  # Logging
  sleuth:
    sampler:
      probability: 0.2  # 20.0% Sampling
  zipkin:
    enabled: ${ZIPKIN_ENABLED:true}
    base-url: ${ZIPKIN_SERVER:http://localhost:9411/}


zuul:
  routes:
    microservices-accounts-ms:
      path: /accounts-ms/**
      serviceId: accounts-ms
      stripPrefix: false
    microservices-auth-ms:
      path: /auth-ms/**
      serviceId: auth-ms
      stripPrefix: false
      # Remove Authorization from sensitiveHeaders
      sensitiveHeaders: Cookie,Set-Cookie


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    instance:
      metadataMap:
        instanceId: ${spring.application.name}:${server.port}
    registerWithEureka: true
    healthcheck:
      enabled: true
    fetchRegistry: false


error:
  whitelabel:
    enabled: false
